# Generated by Django 6.0.3 on 2026-03-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_garden', 'Home & Garden'), ('collectibles', 'Collectibles'), ('vehicles', 'Vehicles'), ('toys', 'Toys & Hobbies'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
