# Generated by Django 6.0.3 on 2026-03-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='notified_ending_soon',
            field=models.BooleanField(default=False),
        ),
    ]
