# Generated by Django 6.0.3 on 2026-04-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_add_deposit_fields'),
        ('auctions', '0006_listing_notified_ending_soon'),
    ]

    operations = [
    ]
